# Generated by Django 6.0.4 on 2026-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='video',
        ),
        migrations.AddField(
            model_name='gallery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
