# Generated by Django 6.0.4 on 2026-05-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_gallery_image_remove_gallery_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=models.FileField(default='cancelled', upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
